name: Say Hello

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run make say-hello
        run: make say-hello